- name: Installar salt-minion
  hosts: nodes

  tasks:
        - name: adicionar repositorio
          yum:
            name: https://repo.saltstack.com/yum/redhat/salt-repo-latest.el7.noarch.rpm
            state: present

        - name: instalar salt-minion
          yum:
            name: salt-minion
            state: latest

        - name: Adicionar salt-master
          lineinfile:
            path: /etc/salt/minion
            insertafter: '^#master: '
            line: master: 192.168.10.30

        - name: Adicionar minion ID
          lineinfile:
            path: /etc/salt/minion
            insertafter: '^#id: '
            line: id: {{inventory_hostname}}

        - name: Iniciar salt-minion
          service:
            name: salt-minion
            state: started
