- name: Installar salt-minion
  hosts: all

  tasks:
        - name: adicionar repositorio
          yum:
            name: https://repo.saltstack.com/yum/redhat/salt-repo-latest.el7.noarch.rpm
            state: present

        - name: instalar salt-minion
          yum:
            name: salt-minion
            state: latest

        - name: Adicionar salt-master
          lineinfile:
            path: /etc/salt/minion
            insertafter: '^#master: '
            line: 'master: 192.168.10.30'

        - name: Adicionar minion ID
          lineinfile:
            path: /etc/salt/minion
            insertafter: #id:
            line: 'id: {{ansible_fqdn}}'

        - name: Iniciar salt-minion
          service:
            name: salt-minion
            state: started
- name: Aceitar todas as chaves de minions
  hosts: localhost

  tasks:
        - name: aceitar as chaves dos minions
          shell: salt-key -A -y
